PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX http: <http://www.w3.org/2011/http#>
PREFIX : <http://example.org/kulturarena/>

# CQ5: Welchem Genre ist der Musikdarbieter mit dem Namen Yasmine Hamdan zuzuordnen und wie lautet die MusicBrainz artist ID?
# Musikdarbietern-IRI, Genre-Name, MusicBrainz artist ID

SELECT ?darbieter ?genrename ?artistID WHERE{
  ?darbieter :hatName ?name ;
             :hatGenre ?genre ;
             :hatMusicBrainzArtistId ?artistID .
  FILTER(?name="Yasmine Hamdan"@de) .
  ?genre :hatName ?genrename .
}
