PREFIX ex: <http://example.org/kulturarena/>

SELECT ?year ((COUNT(?femaleArtist) / COUNT(?artist)) AS ?femaleProportion) ((COUNT(?maleArtist) / COUNT(?artist)) AS ?maleProportion)
WHERE {
  ?concert ex:hatDatum ?year .
  ?concert ex:hatKuenstler ?artist .
  
  OPTIONAL {
    ?femaleArtist ex:hatGeschlecht ex:Weiblich .
    ?concert ex:hatKuenstler ?femaleArtist .
  }
  OPTIONAL {
    ?maleArtist ex:hatGeschlecht ex:Maennlich .
    ?concert ex:hatKuenstler ?maleArtist .
  }
}
GROUP BY (?year)
