PREFIX ex: <http://example.org/kulturarena/>

SELECT ?country (COUNT(?concert) AS ?count)
WHERE {
  ?concert ex:hatKuenstler ?artist.
  ?artist ex:ausLand ?country.
  ?concert ex:hatDatum ?date.
  FILTER (?date = 2015)
}
GROUP BY ?country

