PREFIX rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl:  <http://www.w3.org/2002/07/owl#>
PREFIX xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX :     <http://example.org/kulturarena/>
# CQ5: Welchem Genre ist der Musikdarbieter mit dem Namen 
#      Yasmine Hamdan zuzuordnen und wie lautet die MusicBrainz 
#      artist ID?
#      (Musikdarbietern-IRI, Genre-Name, MusicBrainz artist ID)
SELECT ?mdIRI ?genreName ?mbAID WHERE {
  ?mdIRI a/rdfs:subClassOf* :Musikdarbieter ;
    rdfs:label "Yasmine Hamdan" ;
    :hatGenre ?genreName ;
    :hatMusicBrainzArtistID ?mbAID .
}