PREFIX rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl:  <http://www.w3.org/2002/07/owl#>
PREFIX xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX :     <http://example.org/kulturarena/>
# CQ3: Wieviele Konzerte mit Musikdarbietern aus welchen 
#      Ländern fanden im Jahr 2015 statt?
#      (Land-IRI, Land-Name, Anzahl)
SELECT ?landIRI ?landName (COUNT(DISTINCT ?konzert) AS ?Anzahl) WHERE {
  ?konzert a :Konzert ;
    :hatMusikdarbieter ?musikdarbieter ;
    :hatDatum "2015"^^xsd:gYear .
  ?musikdarbieter :hatLand ?landIRI .
  ?landIRI rdfs:label ?landName .
}
GROUP BY ?landIRI ?landName