PREFIX rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl:  <http://www.w3.org/2002/07/owl#>
PREFIX xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX :     <http://example.org/kulturarena/>
# CQ8: Welche Musikdarbieter stammen aus dem bevölkerungsreichsten 
#      vertretenen Land?
#      (Musikdarbietern-IRI, Musikdarbietern-Name, Herkunftsland-Name)
SELECT ?musikdarbieter ?mdName ?landName WHERE {
  ?musikdarbieter a/rdfs:subClassOf* :Musikdarbieter ;
    rdfs:label ?mdName ;
    :hatLand ?land .
  ?land rdfs:label ?landName ;
    :hatBevoelkerung ?bev .
} 
ORDER BY DESC(?bev) 
LIMIT 1